"""empty message

Revision ID: 37d935598b2d
Revises: a549d27194bc
Create Date: 2016-10-18 22:31:38.102879

"""

# revision identifiers, used by Alembic.
revision = '37d935598b2d'
down_revision = 'a549d27194bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('lname', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('user')
    op.add_column('stores', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'users', ['users_id'], ['user_id'])
    op.drop_column('stores', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'user', ['user_id'], ['id'])
    op.drop_column('stores', 'users_id')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
